name: Deploy Laravel to cPanel (Artifact Method)

on:
  push:
    branches:
      - main

jobs:
  prepare-code-artifact:
    name: Prepare Code Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare code artifact
        run: |
          mkdir ../deploy-code
          rsync -a . ../deploy-code/ \
            --exclude='vendor/' \
            --exclude='node_modules/' \
            --exclude='public/' \
            --exclude='resources/' \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='tests/' \
            --exclude='package*.json' \
            --exclude='vite.config.js' \
            --exclude='storage/' \
            --exclude='phpunit.xml' \
            --exclude='*.bat' \
            --exclude='*.code-workspace' \
            --exclude='**/.*'
          find . -name ".htaccess" -exec cp --parents {} ../deploy-code/ \;
          mv ../deploy-code .

      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-artifact
          path: ./deploy-code
          include-hidden-files: true

  deploy-code:
    name: Deploy Code
    needs: prepare-code-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)
          RUN_ID=${{ github.run_id }}

          ARTIFACT_ID=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts \
            | jq --argjson run_id "$RUN_ID" --arg name "code-artifact" \
              '.artifacts[] | select(.name == $name and .workflow_run.id == $run_id) | .id' \
            | sort -n | tail -1)

          if [ -z "$ARTIFACT_ID" ]; then
            echo "Artifact not found for code."
            exit 1
          fi

          curl --fail-with-body "https://deklarant.zavlan.org/download-deploy.php?artifact=$ARTIFACT_ID&dest=."

  prepare-resources-artifact:
    name: Prepare Resources Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare resources artifact
        run: |
          mkdir -p ./deploy-resources/app-service-laravel
          cp -r ./app-service-laravel/resources ./deploy-resources/app-service-laravel/

      - name: Upload resources artifact
        uses: actions/upload-artifact@v4
        with:
          name: resources-artifact
          path: ./deploy-resources

  deploy-resources:
    name: Deploy Resources
    needs: prepare-resources-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Deploy resources artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)
          RUN_ID=${{ github.run_id }}

          ARTIFACT_ID=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts \
            | jq --argjson run_id "$RUN_ID" --arg name "resources-artifact" \
              '.artifacts[] | select(.name == $name and .workflow_run.id == $run_id) | .id' \
            | sort -n | tail -1)

          if [ -z "$ARTIFACT_ID" ]; then
            echo "Artifact not found for resources."
            exit 1
          fi

          curl --fail-with-body "https://deklarant.zavlan.org/download-deploy.php?artifact=$ARTIFACT_ID&dest=."

  run-composer-install:
    name: Run Composer Install
    needs: deploy-code
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote composer install
        run: |
          curl --fail-with-body "https://deklarant.zavlan.org/run-composer-install.php"

  run-migrations:
    name: Run Laravel Migrations
    needs: run-composer-install
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote migrations
        run: |
          curl --fail-with-body "https://deklarant.zavlan.org/run-migrations.php"

  prepare-js-artifact:
    name: Prepare JS Artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-service-laravel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM packages
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Upload JS artifact
        uses: actions/upload-artifact@v4
        with:
          name: js-artifact
          path: ./app-service-laravel/public/
          include-hidden-files: true

  deploy-js:
    name: Deploy JS Build
    needs: prepare-js-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JS artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)
          RUN_ID=${{ github.run_id }}

          ARTIFACT_ID=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts \
            | jq --argjson run_id "$RUN_ID" --arg name "js-artifact" \
              '.artifacts[] | select(.name == $name and .workflow_run.id == $run_id) | .id' \
            | sort -n | tail -1)

          if [ -z "$ARTIFACT_ID" ]; then
            echo "Artifact not found for JS build."
            exit 1
          fi

          curl --fail-with-body "https://deklarant.zavlan.org/download-deploy.php?artifact=$ARTIFACT_ID&dest=./app-service-laravel/public"