name: Deploy Laravel to cPanel via FTP

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-service-laravel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Upload source code and build artifacts
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./app-service-laravel
          server-dir: /
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/package*.json
            **/vite.config.js
            **/resources/**
            **/public/storage/**
            !public/build/**

      - name: Upload vendor folder
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./app-service-laravel/vendor
          server-dir: /vendor
