name: Deploy Laravel to cPanel (Artifact Method)

on:
  push:
    branches:
      - main

jobs:
  upload-code:
    name: Upload Laravel Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare code artifact
        run: |
          mkdir deploy-code
          rsync -a ./ deploy-code \
            --exclude='vendor/' \
            --exclude='node_modules/' \
            --exclude='public/build/' \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='tests/' \
            --exclude='package*.json' \
            --exclude='vite.config.js' \
            --exclude='resources/' \
            --exclude='storage/' \
            --exclude='phpunit.xml' \
            --exclude='.*' \
            --exclude='*.bat' \
            --exclude='*.code-workspace'

      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-artifact
          path: ./deploy-code

      - name: Call deploy script for code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)

          ARTIFACT_ID=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts \
            | jq '.artifacts[] | select(.name == "code-artifact") | .id')

          curl -f "https://deklarant.ba/deploy-download.php?artifact=$ARTIFACT_ID&dest=."

  upload-vendor:
    name: Upload Vendor Folder
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-service-laravel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies (no dev)
        run: composer install --no-dev --optimize-autoloader

      - name: Upload vendor artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor-artifact
          path: ./app-service-laravel/vendor/

      - name: Call deploy script for vendor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)

          ARTIFACT_ID=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts \
            | jq '.artifacts[] | select(.name == "vendor-artifact") | .id')

          curl -f "https://deklarant.ba/deploy-download.php?artifact=$ARTIFACT_ID&dest=app-service-laravel/vendor"

  upload-js:
    name: Upload JS Build (Vite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-service-laravel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM packages
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Upload JS artifact
        uses: actions/upload-artifact@v4
        with:
          name: js-artifact
          path: ./app-service-laravel/public/build/

      - name: Call deploy script for JS build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_FULL="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO_FULL" | cut -d'/' -f2)

          ARTIFACT_ID=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts \
            | jq '.artifacts[] | select(.name == "js-artifact") | .id')

          curl -f "https://deklarant.ba/deploy-download.php?artifact=$ARTIFACT_ID&dest=app-service-laravel/public/build"
